# Generated by Django 4.2.3 on 2023-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content_type', models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('assigment', 'Домашнее задание')], max_length=20)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
