# Generated by Django 4.2.3 on 2023-07-31 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('employment_status', models.CharField(blank=True, max_length=150)),
                ('highest_degree', models.CharField(blank=True, max_length=150)),
                ('field_or_major', models.CharField(blank=True, max_length=150)),
                ('about_me', models.TextField(blank=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=300)),
                ('youtube_link', models.URLField(blank=True, max_length=300)),
                ('twitter_link', models.URLField(blank=True, max_length=300)),
                ('facebook_link', models.URLField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
